markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: 我还没有吃到奇奇怪怪味的小浣熊
host: ilovelll.github.io
desc: 你好，我是李红恩，欢迎来到我的博客。

custom:
    category:
        python: Python学习
        git: Git学习
        daily: 字里行间
    categories:
      - name:  python
        title: Python学习

      - name:  git
        title: Git学习

      - name:  daily
        title: 字里行间
    scrollingLoadCount: 2                           # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: ilovelll
        email: gradle@qq.com
        disqus: ilovelll                            # Disqus缩略标识
        gcse: 000165500900005941458:fs-6mdjey0o     # Google自定义搜索标识ID
        github: ilovelll                            # GitHub账号
        gravatar: 57a743021e2fdbae6b0e05bbddb2398c  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
